---
title: "R Notebook"
output: html_notebook
---

Author: Dr Jasmine Wilson
Script for plotting cytomap statistical data for T cells v CXCL9 


```{r setup}
#Load library
pacman::p_load(dplyr, inspectdf, visdat, readr, tidyverse, DataExplorer, tidyr, plyr,epiDisplay, showtext, ggplot2,plotly, LaCroixColoR, gridExtra, ggrepel, plotly, ggtext, png, tidyverse, magrittr, magick, devtools, curl, data.table,  lubridate, ggExtra, cowplot )
font_add_google("Lora", "Lora")
showtext_opts(dpi = 320)
showtext_auto()

#install_github("johannesbjork/LaCroixColoR")
```
# Set directory 

```{r}
getwd()
setwd()
getwd()
```


Plots per sample basis
```{r}
#Defining plot themes

my_theme <-     theme(
    panel.grid.major = element_blank(), 
    panel.grid.minor = element_blank(),
    panel.background = element_rect(fill="white"),
    plot.background  = element_rect(fill = "white"),
    plot.margin = margin(6, 6, 6, 6, "cm"),
    axis.line = element_line(size = 1, colour = "#00052C", linetype=1),
    axis.text.x  = element_text( angle = 90, color="#00052C", size=20, face=1,  family = "Lora"),
    axis.text.y  = element_text( angle = 0, color="#00052C", size=20, face=1, family = "Lora"),
    axis.title.x = element_text(color="#00052C", size=20, face=1, margin=margin(t=20), family = "Lora"),
    axis.title.y = element_text(color="#00052C", size=20, face=1, margin=margin(r=20), family = "Lora"),
    plot.title = element_text(colour = "#00052C",size=25, face= "bold", family = "Nosifer", hjust =0, vjust = 0),
    plot.subtitle = element_text(colour = "#00052C",size=40, face=1, family = "Lora", hjust =0.5,vjust = 3),
    plot.caption = element_text(color = "#00052C", face = "italic",size=25, family = "Lora",hjust =-0.5,vjust = 3),
    legend.position = "bottom",
        legend.key.size   = unit(2, 'cm'), #change legend key size
        legend.key.height = unit(1, 'cm'), #change legend key height
        legend.key.width  = unit(1, 'cm'), #change legend key width
        legend.title      = element_text(size=14), #change legend title font size
        legend.text       = element_text(size=14), #change legend text font size
    strip.text.x = element_text(size = 12, color = "#00052C", face = "bold"),
    strip.background = element_rect(color="white", fill="#bf3d3d", size=1.5, linetype="solid")
    #plot.margin=unit(c(0,8,1,1),"lines")
    # t= 0, r = 0, b = 0, l = 0, unit = "pt"
    ) 


my_theme_vol <-     theme(
    panel.grid.major = element_blank(), 
    panel.grid.minor = element_blank(),
    panel.background = element_rect(fill="white"),
    plot.background  = element_rect(fill = "white"),
    plot.margin = margin(1, 1, 1, 1, "cm"),
    axis.line = element_line(size = 1, colour = "#00052C", linetype=1),
    axis.text.x  = element_text( angle = 90, color="#00052C", size=20, face=1,  family = "Lora"),
    axis.text.y  = element_text( angle = 0, color="#00052C", size=20, face=1, family = "Lora"),
    axis.title.x = element_text(color="#00052C", size=20, face=1, margin=margin(t=20), family = "Lora"),
    axis.title.y = element_text(color="#00052C", size=20, face=1, margin=margin(r=20), family = "Lora"),
    plot.title = element_text(colour = "#00052C",size=25, face= "bold", family = "Nosifer", hjust =0, vjust = 0),
    plot.subtitle = element_text(colour = "#00052C",size=40, face=1, family = "Lora", hjust =0.5,vjust = 3),
    plot.caption = element_text(color = "#00052C", face = "italic",size=25, family = "Lora",hjust =-0.5,vjust = 3),
    legend.position = "bottom",
        legend.key.size   = unit(2, 'cm'), #change legend key size
        legend.key.height = unit(1, 'cm'), #change legend key height
        legend.key.width  = unit(1, 'cm'), #change legend key width
        legend.title      = element_text(size=14), #change legend title font size
        legend.text       = element_text(size=14), #change legend text font size
    strip.text.x = element_text(size = 12, color = "#00052C", face = "bold"),
    strip.background = element_rect(color="white", fill="#bf3d3d", size=1.5, linetype="solid")
    #plot.margin=unit(c(0,8,1,1),"lines")
    # t= 0, r = 0, b = 0, l = 0, unit = "pt"
    ) 

var = 'CytoMAP_D18_3_1'

for (var in c('CytoMAP_D18_1_2',
              'CytoMAP_D18_2_1',
              'CytoMAP_D18_3_1',
              'CytoMAP_D18_4_3',
              'CytoMAP_D18_6_3',
              'CytoMAP_D18_8_2',
              'CytoMAP_D25_2_1',
              'CytoMAP_D25_11_1',
              'CytoMAP_D25_12_1',
              'CytoMAP_D25_blank'
              ))
  
  {

df <- readr::read_csv(paste0('./20220419_RDP/',var,'.csv'))

#gates

df$celltype = 'unknown'
df[df$CD8_SC_CD8_cells == 1, 'celltype'] <- 'cd8'
df[df$Gate_All_Rand_New_Random_Points_RDP == 1, 'celltype'] <- 'rdp'
df[df$CD8_cells_CD8_cell_CXCR3POS   == 1, 'celltype'] <- 'cd8_cxcr3pos'
df[df$CD8_cells_CD8_cell_CXCR3NEG   == 1, 'celltype'] <- 'cd8_cxcr3neg'
df[df$CXCL9_CXCR3NEG_CXCL9_DIFFUSE  == 1, 'celltype'] <- 'cxcl9_diffuse'
df[df$CXCL9_CXCR3NEG_CXCL9_CELLULAR == 1, 'celltype'] <- 'cxcl9_cellular'
df[df$CXCR3_CXCL9NEG_CXCR3_CD8POS   == 1, 'celltype'] <- 'cxcr3pos_cd8pos'
df[df$CXCR3_CXCL9NEG_CXCR3_CD8NEG   == 1, 'celltype'] <- 'cxcr3pos_cd8neg'


####  RDP  _____________________________________________________________________

p1 <- df %>% subset(celltype %in% 'rdp') %>% 
            ggplot(aes(x = DistTo_CXCL9_CXCR3NEG_CXCL9_DIFFUSE,
                       y = DistTo_CXCL9_CXCR3NEG_CXCL9_CELLULAR, 
                       color = celltype)) +
            geom_point(alpha=1) +
            guides(colour = guide_legend(override.aes = list(size=10))) +
            ggtitle(label = "RDP distance to cellular and diffuse CXCL9") + 
            ylab(label = "Distance to CXCL9 Cellular")+
            xlab(label = "Distance to CXCL9 Diffuse") +
            xlim(0, 350) +
            ylim(0, 550) + 
  my_theme

p1 <- ggExtra::ggMarginal(p1,  groupColour = TRUE, groupFill = TRUE)

#ggsave(p, filename = paste0("./20220419_plots/20220420_setaxis_plots/dist_cxcl9_RDP_", var ,".tiff"), height = 6, width = 10)
                     

####  All pop   ________________________________________________________________

p2 <- df %>% subset (celltype %in% c("cd8_cxcr3neg",
                                     "cd8_cxcr3pos" )) %>% 
            ggplot(aes(x = DistTo_CXCL9_CXCR3NEG_CXCL9_DIFFUSE,
                       y = DistTo_CXCL9_CXCR3NEG_CXCL9_CELLULAR, 
                       color = celltype)) +
            geom_point(alpha=0.6) +
            guides(colour = guide_legend(override.aes = list(size=10))) +
            ggtitle(label = "CD8 CXCR3 +/- distance to cellular and diffuse CXCL9") + 
            ylab(label = "Distance to CXCL9 Cellular")+
            xlab(label = "Distance to CXCL9 Diffuse") +
            xlim(0, 350) +
            ylim(0, 550) + 
  my_theme

p2 <- ggExtra::ggMarginal(p2,  groupColour = TRUE, groupFill = TRUE)



####  CD8 pop / CXCL9   ________________________________________________________________

p3 <- df %>% subset(celltype %in% c( "cxcr3pos_cd8neg", "cxcr3pos_cd8pos")) %>%  
            ggplot(aes(x = DistTo_CXCL9_CXCR3NEG_CXCL9_DIFFUSE,
                       y = DistTo_CXCL9_CXCR3NEG_CXCL9_CELLULAR, 
                       color = celltype)) +
            geom_point(alpha=0.6) +
            guides(colour = guide_legend(override.aes = list(size=10))) +          
            ggtitle(label = "CXCR3 +/- CD8 cell distance to cellular and diffuse CXCL9") + 
            ylab(label = "Distance to CXCL9 Cellular")+
            xlab(label = "Distance to CXCL9 Diffuse") +
            xlim(0, 350) +
            ylim(0, 550) + 
  my_theme

p3 <- ggExtra::ggMarginal(p3,  groupColour = TRUE, groupFill = TRUE)




####  RDP / tissue border  ________________________________________________________________

p5 <- df %>% subset(celltype %in% c("rdp")) %>%  
            ggplot(aes(x = DistToUDS_Tissue,
                       y = DistTo_CXCL9_CXCR3NEG_CXCL9_DIFFUSE, 
                       color = celltype)) +
            geom_point(alpha=1) +
            guides(colour = guide_legend(override.aes = list(size=10))) +
            ggtitle(label = "RDP distance to tumor border v diffuse CXCL9") + 
            ylab(label = "Distance to CXCL9 Diffuse") +
            xlab(label = "DistToUDS_Tissue") +
            xlim(0, 700) +
            ylim(0, 350) + 
            my_theme

p5 <- ggExtra::ggMarginal(p5,  groupColour = TRUE, groupFill = TRUE)


####  all pop / tissue border  ________________________________________________________________

p6 <- df %>% subset(celltype %in% c("cd8_cxcr3pos", "cd8_cxcr3neg", 
                                    "cxcr3pos_cd8neg", "cxcr3pos_cd8pos")) %>%  
            ggplot(aes(x = DistToUDS_Tissue,
                       y = DistTo_CXCL9_CXCR3NEG_CXCL9_DIFFUSE, 
                       color = celltype)) +
            geom_point(alpha=1) +
            guides(colour = guide_legend(override.aes = list(size=10))) +
            ggtitle(label = "Cell distance to tumor border v diffuse CXCL9") + 
            ylab(label = "Distance to CXCL9 Diffuse") +
            xlab(label = "DistToUDS_Tissue") +
            xlim(0, 700) +
            ylim(0, 350) + 
            my_theme

p6 <- ggExtra::ggMarginal(p6,  groupColour = TRUE, groupFill = TRUE)


####  CD8 pop / tissue border  ________________________________________________________________

p7 <- df %>% subset(celltype %in% c("cd8_cxcr3pos", "cd8_cxcr3neg")) %>%  
            ggplot(aes(x = DistToUDS_Tissue,
                       y = DistTo_CXCL9_CXCR3NEG_CXCL9_DIFFUSE, 
                       color = celltype)) +
            geom_point(alpha=1) +
            guides(colour = guide_legend(override.aes = list(size=10))) +
            ggtitle(label = "CD8 distance to tumor border v diffuse CXCL9") + 
            ylab(label = "Distance to CXCL9 Diffuse")+
            xlab(label = "DistToUDS_Tissue") +
            xlim(0, 700) +
            ylim(0, 350) + 
            my_theme

p7 <- ggExtra::ggMarginal(p7,  groupColour = TRUE, groupFill = TRUE)


#cowplot


cp <- cowplot::plot_grid(p1, p2, p3, p5, p6, p7, 
                         labels = c('A', 'B', 'C', 'D', 'E', 'F'), 
                         label_size = 12, 
                          ncol = 3)  + 
              theme(plot.margin = unit(c(3,3,3,3,3,3), "lines"))
                        # rel_heights = c(0.5,0.5,0.5,1.5,0.5,0.5,0.5,1.5),
                        # rel_widths = c(1,1,1,1.5, 1,1,1,1.5))

ggsave2(cp, filename = paste0("./20220419_plots/20220420_setaxis_plots/", var, ".pdf"), height = 20, width =45)

#________________________________________________________________
#________________________________________________________________


####  CD8 cell size CXCL9 diffuse  

p4 <- df %>% subset(celltype %in% c("cd8_cxcr3pos", "cd8_cxcr3neg")) %>%  
  
  ggplot(aes(x = DistTo_CXCL9_CXCR3NEG_CXCL9_DIFFUSE, 
             y = DistTo_CXCL9_CXCR3NEG_CXCL9_CELLULAR, 
             color = celltype, 
             size = Volume)) +
    ggtitle(label = "Activated CD8 cells and distance to cellular and diffuse CXCL9") +
    geom_point(alpha=0.6) +
  guides(colour = guide_legend(override.aes = list(size=10))) +
    scale_size(range = c(1, 15), name="Cell volume") +
  #, limits = c(500, 4000)
   # scale_size_continuous(limits=c(100,2000),breaks=c(1000,1500)) +
     ylab(label = "Distance to CXCL9 Cellular")+
     xlab(label = "Distance to CXCL9 Diffuse") +
     xlim(0, 350) +
     ylim(0, 550) +
     my_theme_vol


####  CD8 pop vol / tissue border / CXCL9 diffuse  

p8 <- df %>% subset(celltype %in% c("cd8_cxcr3pos", "cd8_cxcr3neg")) %>%  
  
  ggplot(aes(x = DistTo_CXCL9_CXCR3NEG_CXCL9_DIFFUSE, 
             y = DistToUDS_Tissue, 
             color = celltype, 
             size = Volume)) +
  
  geom_point(alpha=0.6) +
  guides(colour = guide_legend(override.aes = list(size=10))) +
  ggtitle(label = "Activated CD8 cells and distance to tumor border v diffuse CXCL9") +
  scale_size(range = c(1, 15), name="Cell volume") +
  #, limits = c(500, 4000)
# scale_size_continuous(limits=c(1, 400),breaks=c(100,200,300,400)) +
  ylab(label = "Distance to border")+
  xlab(label = "Distance to CXCL9 Diffuse") +
            xlim(0, 350) +
            ylim(0, 450) + 
   my_theme_vol

####  CD8 pop vol / tissue border / CXCL9 diffuse  

p8b <- df %>% subset(celltype %in% c("cd8_cxcr3pos", "cd8_cxcr3neg")) %>%  
  
  ggplot(aes(x = DistTo_CXCL9_CXCR3NEG_CXCL9_CELLULAR, 
             y = DistToUDS_Tissue, 
             color = celltype, 
             size = Volume)) +
  
  geom_point(alpha=0.6) +
 guides(colour = guide_legend(override.aes = list(size=10))) +
  ggtitle(label = "Activated CD8 cells and distance to tumor border v cellular CXCL9") +
  scale_size(range = c(1, 15), name="Cell volume") +
  #, limits = c(500, 4000)
 # + scale_size_continuous(limits=c(1,30),breaks=c(5,10,20,30)) 
  ylab(label = "Distance to border")+
  xlab(label = "Distance to CXCL9 Cellular") +
            xlim(0, 600) +
            ylim(0, 550) + 
   my_theme_vol


#cowplot


cp2 <- cowplot::plot_grid(p4, NULL,  p8, p8b, 
                         labels = c('A', 'C', 'D'), 
                         label_size = 12, 
                          ncol = 2)  
                        # rel_heights = c(0.5,0.5,0.5,1.5,0.5,0.5,0.5,1.5),
                        # rel_widths = c(1,1,1,1.5, 1,1,1,1.5))

ggsave2(cp2, filename = paste0("./20220419_plots/20220420_setaxis_plots/vol_", var, ".pdf"), height = 20, width =30)
}




```


